### ISSUE TITLE
/clubs/{club_id}/players Internal Server error

### ISSUE THREAD

**Issue by tguswell** [felipeall/transfermarkt-api#93]
Hi

I'm getting "Internal Server Error" in multiple requests , /clubs/{club_id}/players. It appears to be similar to issue #91 but on listing squad information. It only affects some clubs.

Many thanks

**Comment by tguswell** [comment]
For reference, one of the club_id's I'm trying to use is 92011.

**Comment by felipeall** [comment]
Hi @tguswell thanks for reporting this issue, it is fixed now

**Comment by ADNAN-an** [comment]
![Image](https://github.com/user-attachments/assets/9839fb11-2788-484c-8657-9fd3e212e97d)

Hello @felipeall , 
I'm actually still getting the error , for some clubs , and for some players too , while it was working perfectly fine like a month ago.

**Comment by tguswell** [comment]
> Hi [@tguswell](https://github.com/tguswell) thanks for reporting this issue, it is fixed now

I'm sorry but I'm still getting the internal server error on both the online version and the version I've downloaded and running locally. An example club id is 92011.

**Comment by ADNAN-an** [comment]
@tguswell Same , i'm still facing the same issues

**Comment by felipeall** [comment]
@tguswell @ADNAN-an sorry guys, it was a bug related to players with no dob/age. I just deployed a fix for it, please let me know if you face any errors again

**Comment by ADNAN-an** [comment]
@felipeall I'm sorry but the error is still occurrent, with the clubs profile too , just like you can see in the picture , i'm trying to access the profile of this club 12721 , but i'm getting "Internal Server Error".

![Image](https://github.com/user-attachments/assets/2b94b1c7-c612-46a4-b4fd-e2ea6cedb621)

**Comment by tguswell** [comment]
@felipeall Many thanks this has cured my problem. Just a thought but for lower league team/players should the majority of information for them be optional?

**Comment by felipeall** [comment]
@ADNAN-an I just fixed this issue too (missing team official name and founding date)

@tguswell Yes, that makes sense. I implemented Pydantic recently in order to manage the data models but I didn't have time yet to find out what should be the optional fields...

**Comment by ADNAN-an** [comment]
@felipeall I don't know why the error is still happening for players profile , everything was working like a month ago but i don't know what changed , i hope it's fixable , thank you again.

![Image](https://github.com/user-attachments/assets/2dd6696f-3607-458a-9f62-d7936cf16453)
